on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: dELIKEEb firmware (Waaffle/Vanana)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: 'docker://zmkfirmware/zmk-build-arm:2.5'
        id: west-init
        with:
          args: 'init "-l config"'
      - name: West Update
        uses: 'docker://zmkfirmware/zmk-build-arm:2.5'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zmk-build-arm:2.5'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zmk-build-arm:2.5'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'
      
      - name: West Build (waaffle_rev3)
        uses: 'zmkfirmware/zmk-build-arm:2.5'
        id: west-build-waaffle_rev3
        with:
          args: 'build "-s zmk/app -b nice_nano -- -DSHIELD=waaffle_rev3 -DZMK_CONFIG=/github/workspace/config"'
      - name: waaffle_rev3 DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano.dts.pre.tmp
      - name: waaffle_rev3 Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 waaffle_rev3.uf2
      - name: Archive (waaffle_rev3)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: waaffle_rev3.uf2
          
      - name: delete compilation residue
        run: sudo rm -rf build/zephyr/*
          
      - name: West Build (vanana_rev2)
        uses: 'docker://zmkfirmware/zmk-build-arm:2.5'
        id: west-build-vanana_rev2
        with:
          args: 'build "-s zmk/app -p -b nice_nano -- -DSHIELD=vanana_rev2 -DZMK_CONFIG=/github/workspace/config"'
      - name: vanana_rev2 DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano.dts.pre.tmp
      - name: vanana_rev2 Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 vanana_rev2.uf2
      - name: Archive (vanana_rev2)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: vanana_rev2.uf2
