on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: dELIKEEb firmware (Waaffle/Vanana)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      
      - name: West Build (waaffle_rev3)
        run: west build "-s zmk/app -b nice_nano -- -DSHIELD=waaffle_rev3 -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: waaffle_rev3 DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/.dts.pre.tmp
      - name: waaffle_rev3 Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 waaffle_rev3.uf2
      - name: Archive (waaffle_rev3)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: waaffle_rev3.uf2
          
      - name: delete compilation residue
        run: sudo rm -rf build/zephyr/*
          
      - name: West Build (vanana_rev2)
        run: west build "-s zmk/app -b nice_nano -- -DSHIELD=vanana_rev2 -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"       
      - name: vanana_rev2 DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/.dts.pre.tmp
      - name: vanana_rev2 Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 vanana_rev2.uf2
      - name: Archive (vanana_rev2)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: vanana_rev2.uf2
